project:
  type: website

website:
  title: ""
  navbar:
    background: secondary
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects
      - href: blog.qmd
        text: Blog
      - href: interests.qmd
        text: Interests
      - href: about.qmd
        text: About Me

format:
  html:
    theme:
    - default
    - themes/styles.scss
    toc: true